# Basic
name:               "ML lab @ CU Denver"
title:              "Machine Learning Lab"
description:        ""


# URL
url:                http://ml.cse.ucdenver.edu/
baseurl:             
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "research"
    href:           "/research"
  - name:           "people"
    href:           "/people"
  - name:           "talks"
    href:           "/talks"
  - name:           "news"
    href:           "/news"
  - name:           "resources"
    href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"
  -
    scope:
      path:         ""
      type:         "research"
    values:
      layout:       "research"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
  research:
    output: true
    permalink: /research/:title/index.html

#Please make sure to install the plugin with gem before listing below
#$ gem install jekyll-last-modified-at
#Also, list the plugin in the Gemfile in the following group:
#group :jekyll_plugins do
#  gem "jekyll-last-modified-at"
#end
#
plugins:
  - jekyll-last-modified-at

# Enable safe mode
safe: true

# Whitelist plugins under safe mode.
# Note that `some-other-jekyll-plugin` is not listed here. Therefore,
# it will not be loaded under safe mode.
whitelist:
  - jekyll-last-modified-at